### ISSUE TITLE
How to make the whole panel https?

### ISSUE THREAD

**Issue by thedarkcr0w** [MCSManager/MCSManager#851]
How would i go around making the panel https, deamon keeps throwing error when i do so?

**Comment by thedarkcr0w** [comment]
![chrome_6DKqwRm0dA](https://user-images.githubusercontent.com/100016905/226818995-7d8ce0a8-653e-4c02-a30b-1c9b258dd3dc.png)

**Comment by unitwk** [comment]
https://docs.mcsmanager.com/#/tutorial/reverse-proxy-ssl

Maybe this will help you, good luck.

**Comment by thedarkcr0w** [comment]
![chrome_t7sX2PLhSI](https://user-images.githubusercontent.com/100016905/226821448-8abe3784-61e4-43ea-8f9f-528c04d9d93f.png)

**Comment by thedarkcr0w** [comment]
am i doing this wrong?

**Comment by thedarkcr0w** [comment]
when i go to api.karasu.live i can see my demon 
it doesnt respond on wss://api.karasu.live or wss:/api.karasu.live:24444

**Comment by zijiren233** [comment]
> ![chrome_t7sX2PLhSI](https://user-images.githubusercontent.com/100016905/226821448-8abe3784-61e4-43ea-8f9f-528c04d9d93f.png)

proxy port 24444 whit websocket
```nginx proxy
location ^~ /
{
    proxy_pass http://127.0.0.1:24444;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_http_version 1.1;
    # proxy_hide_header Upgrade;
}
```

Then you shoud set address is wss://you.domain,  port is proxy port in mcsmanager

**Comment by thedarkcr0w** [comment]
adding that to custom location made it offline on the proxy

**Comment by thedarkcr0w** [comment]
![chrome_WSbxR32Pac](https://user-images.githubusercontent.com/100016905/226825121-f8123c36-96b6-44c0-a0fa-ac54bd1393c6.png)

**Comment by thedarkcr0w** [comment]
can you explain a bit deeper?

**Comment by unitwk** [comment]
Since you can access https://api.karasu.live normally, but cannot access wws://api.karasu.live, it proves that you have a little problem with the websocket configuration.

Please refer to here, support for Websocket + SSL.

https://docs.mcsmanager.com/#/tutorial/simple-reverse-proxy

Everyone's network environment is somewhat different. We cannot adopt a solution that is suitable for all network environments. Most of them may only be tried and solved by yourself.

**Comment by thedarkcr0w** [comment]
I don't understand why i cannot access wss://api.karasu.live:8443
The demon is on 24444 its reverse proxied to 8443 it still doesnt work
Its accessible from api.karasu.live but not wss://api.karasu.live:8443

**Comment by YipSzeho** [comment]
我也是遇到同样的问题，用https能访问到远程节点，但在面板用wss就不通了

**Comment by YipSzeho** [comment]
发现面板只能用localhost的24444端口连接到节点，nginx把节点的端口映射到别的都不行

**Comment by thedarkcr0w** [comment]
> 我也是遇到同样的问题，用https能访问到远程节点，但在面板用wss就不通了

did  you find a fix?

**Comment by YipSzeho** [comment]
Reverse proxy the daemon to `https://panel.karasu.live:24444` and make sure you can access this URL from your browser. Then add `localhost`:`24444` as a daemon in the MCSM panel.

把守护进程反向代理到`https://panel.karasu.live:24444`，并确认能从浏览器访问这个网址。然后在MCSM面板添加`localhost`:`24444`作为守护进程。

**Comment by Bluemangoo** [comment]
does your proxy work properly? maybe you have only proxied https but not wss. you can test your websocket on online websocket tester (like [piesocket](https://www.piesocket.com/websocket-tester)).

**Comment by thedarkcr0w** [comment]
How do i proxy the wss?

**Comment by thedarkcr0w** [comment]
> Reverse proxy the daemon to `https://panel.karasu.live:24444` and make sure you can access this URL from your browser. Then add `localhost`:`24444` as a daemon in the MCSM panel.
> 
> 把守护进程反向代理到`https://panel.karasu.live:24444`，并确认能从浏览器访问这个网址。然后在MCSM面板添加`localhost`:`24444`作为守护进程。

this didnt work, panel is accessible the https://panel.karasu.live:24444 shows the deamon but it cant connect using https it because ssl doesnt allow ports in url

**Comment by thedarkcr0w** [comment]
![chrome_5msCiEpjRx](https://user-images.githubusercontent.com/100016905/227388466-2b2ab720-965d-48f2-b774-6ce40082bad1.png)

**Comment by thedarkcr0w** [comment]
![chrome_XQEPHQN0gM](https://user-images.githubusercontent.com/100016905/227388493-ea4fec77-dc82-4d3e-84c1-337c214b68b7.png)

**Comment by thedarkcr0w** [comment]
![chrome_51szEEWtWH](https://user-images.githubusercontent.com/100016905/227391232-eed181a4-4637-4de0-a5cc-e42c224b6e44.png)
![chrome_XQEPHQN0gM](https://user-images.githubusercontent.com/100016905/227391234-74a4d057-a54a-46c0-a768-e619e367fc41.png)
![chrome_GL1zVP6HI4](https://user-images.githubusercontent.com/100016905/227391237-1af53aa2-1d1c-439e-a6a0-4f1858e2ef22.png)
![chrome_x1pvrohpaO](https://user-images.githubusercontent.com/100016905/227391238-e8effc03-c94a-4dbc-b72a-cc9dccfc2142.png)

**Comment by thedarkcr0w** [comment]
`proxy_hide_header Upgrade;
proxy_hide_header X-Powered-By;
add_header Content-Security-Policy "upgrade-insecure-requests";
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Cache-Control "no-transform" always;
add_header Referrer-Policy no-referrer always;
add_header X-Robots-Tag none;

location @ws {
proxy_pass http://localhost:24444;
proxy_set_header Host $http_host;
proxy_read_timeout     60;
proxy_connect_timeout  60;
proxy_redirect         off;

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_set_header Host $host;
proxy_cache_bypass $http_upgrade;
}`

**Comment by AleTheTwin** [comment]
I'm facing the same issue, I can access the daemon if I request it directly through https, but I can set the panel to use https, if I use wss://my.domai it simply sends the request to the panel port, instead of using the daemon port I provided.
But, if I remove the "wss://" it actually sends the request to the port, but it does it through http, and the connection fails

![Screenshot 2023-03-30 at 11 37 19 a m](https://user-images.githubusercontent.com/71783206/228918951-d92696b8-bb4b-446e-b6c1-5fdbdae7339e.png)

in both cases the port is set to 8080 (proxy port) in the panel

**Comment by Boris-Karamanolev** [comment]
Any solutions?

**Comment by AleTheTwin** [comment]
Not really, I resigned to follow the marvelous recommendation of keep it insecure

**Comment by bddjr** [comment]
(Translate by fanyi.baidu.com)

Although I haven't translated it into English yet, I think you might try to refer to it  
https://github.com/bddjr/nginx-proxy-docs-for-mcsm/blob/master/配置HTTPS反向代理.md
